- name: Build APK
  run: |
    export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
    export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
    export PATH=$PATH:$ANDROID_HOME/platform-tools
    export PATH=$PATH:$ANDROID_HOME/build-tools/33.0.0

    yes | buildozer android debug
